[project]
site_name = "ElecSolver"
site_description = "Formalizes electric systems as linear problems for temporal and frequency-domain studies."
site_author = "William Piat"
repo_url = "https://github.com/williampiat3/ElecSolver"
repo_name = "GitHub"
docs_dir = "docs"
site_dir = "site"

nav = [
  "index.md",
  { Components = [
    "components/frequency-system-builder.md",
    "components/temporal-system-builder.md",
  ] },
  "solver-suggestions.md",
  "extra-uses-hydraulic-or-thermal-system-modeling.md",
  "netlist-import-feature.md",
]

[project.theme]
name = "zensical"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"