name: Test Python Program

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: test-env
        environment-file: env.yml
        python-version: 3.12  # or whatever version you need
        auto-activate-base: false

    - name: Verify environment
      run: |
        conda info
        conda list

    - name: Run tests
      run: |
        # replace this with your actual test command, e.g., pytest, unittest, etc.
        pytest
