name: Test Python Program

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ElecSolver
        environment-file: env.yml
        auto-activate-base: false
        conda-remove-defaults: "true"

    - name: Verify environment
      run: |
        conda info
        conda list

    - name: Run tests
      run: |
        # replace this with your actual test command, e.g., pytest, unittest, etc.
        pytest
